version: '1'
name: dse24
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
services:
    rabbitmq:
        image: rabbitmq:3.13-management-alpine
        container_name: dse24-rabbitmq
        networks:
            static-network:
                ipv4_address: 172.20.0.10
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 5s
            timeout: 5s
            retries: 5
            
    inventory:
        image: dse24-inventory-service
        build:
            context: ./
            dockerfile: ./src/inventory_service/Dockerfile
        networks:
            static-network:
                ipv4_address: 172.20.0.11
        ports:
            - 8080:80
        healthcheck:
            test: wget --no-verbose --tries=1 --spider  http://172.20.0.11/ || exit 1
            interval: 5s
            timeout: 5s
            retries: 5

    beachcomb:
        image: dse24-beachcomb-service
        build:
            context: ./
            dockerfile: ./src/beachcomb_service/Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            static-network:
                ipv4_address: 172.20.0.12
        ports:
            - 8081:80

    datafeeder:
        image: dse24-data-feeder
        build:
            context: ./
            dockerfile: ./src/data_feeder/Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
            inventory:
                condition: service_healthy
        networks:
            static-network:
                ipv4_address: 172.20.0.13
        ports:
            - 8082:80

    dashboard:
        image: dse24-dashboard-service
        build:
            context: ./
            dockerfile: ./src/dashboard_service/Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            static-network:
                ipv4_address: 172.20.0.14
        ports:
            - 8083:80

    memcached:
        image: memcached:1.6.27-alpine
        container_name: dse24-memcached
        networks:
            static-network:
                ipv4_address: 172.20.0.15
        ports:
            - 11212:11212
        healthcheck:
            test: echo "version" | nc -vn -w 1 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 5
        
    control:
        image: dse24-control-service
        build:
            context: ./
            dockerfile: ./src/control_service/Dockerfile
        depends_on:
            memcached:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            static-network:
                ipv4_address: 172.20.0.16
        ports:
            - 8084:80
