name: Docker run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    name: Run Tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/inventory_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inventory-test:${{ github.sha }}

      - name: Run Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/inventory-test:${{ github.sha }} npm run test
